install:
	git clone https://github.com/dense-analysis/ale.git
	git clone https://github.com/chrisbra/Colorizer.git
	git clone https://github.com/vim-scripts/c.vim.git
	git clone https://github.com/Shougo/denite.nvim.git
	git clone https://github.com/Shougo/deol.nvim.git
	git clone https://github.com/mattn/emmet-vim
	git clone https://github.com/mboughaba/i3config.vim.git
	git clone https://github.com/davidhalter/jedi-vim.git
	git clone https://github.com/davidhalter/jedi.git
	git clone https://github.com/davidhalter/parso.git
	git clone https://github.com/Shougo/neoinclude.vim.git
	git clone https://github.com/Shougo/neosnippet-snippets.git
	git clone https://github.com/Shougo/neosnippet.vim.git
	git clone https://github.com/scrooloose/nerdtree.git
	git clone https://github.com/roxma/nvim-yarp.git
	git clone https://github.com/ervandew/supertab.git
	git clone https://github.com/vim-scripts/svg.vim.git
	git clone https://github.com/godlygeek/tabular.git
	git clone https://github.com/majutsushi/tagbar.git
	git clone https://github.com/SirVer/UltiSnips.git
	git clone https://github.com/mbbill/undotree.git
	git clone https://github.com/Shougo/unite.vim.git
	git clone https://github.com/vim-airline/vim-airline.git
	git clone https://github.com/vim-airline/vim-airline-themes.git
	git clone https://github.com/liuchengxu/vim-clap.git
	git clone https://github.com/flazz/vim-colorschemes
	git clone https://github.com/tpope/vim-commentary.git
	git clone https://github.com/tpope/vim-fugitive.git
	git clone https://github.com/airblade/vim-gitgutter.git
	git clone https://github.com/roxma/vim-hug-neovim-rpc.git
	git clone https://github.com/plasticboy/vim-markdown.git
	git clone https://github.com/terryma/vim-multiple-cursors.git
	git clone https://github.com/sheerun/vim-polyglot.git
	git clone https://github.com/kshenoy/vim-signature.git
	git clone https://github.com/honza/vim-snippets.git
	git clone https://github.com/mhinz/vim-startify.git
	git clone https://github.com/tpope/vim-surround.git
	git clone https://github.com/blindFS/vim-taskwarrior.git
	git clone https://github.com/vimwiki/vimwiki.git
	git clone https://github.com/neoclide/coc.nvim
	rm -v vim-colorschemes/colors/onedark.vim
	sh coc.nvim/install.sh
