.PHONY: install-desktop

# TODO: Install fonts

install-desktop:
	@echo 'Installing elinks config file for desktop (smaller font)'
	mkdir -p ~/.elinks
	cp -iv elinks.conf bookmarks ~/.elinks/
	@echo 'Installation complete!'
