export ZSH='/dev/null'    # zsh:1: command not found: ashe


if [ ! -f /tmp/.zshreload ]; then
    export LANG="en_US.UTF-8"
    #ZSH=/root/.oh-my-zsh/
    ZSH_THEME="powerlevel9k"
    HYPHEN_INSENSITIVE="true"

    # plugins=( colorize zsh-autosuggestions zsh-syntax-highlighting you-should-use )

    # source ~/.oh-my-zsh/oh-my-zsh.sh

    export plugindir=/ashe/zsh/components

    # Set preload vars
    # Line #1863-1864 of main theme file
    $POWERLEVEL9K_IGNORE_TERM_LANG=true
    $POWERLEVEL9K_IGNORE_TERM_COLORS=true

    for file in $(find $plugindir | ack '\.zsh$'); do
        . $file end
    done

    # export EDITOR='vim'
    export EDITOR='nvim'

    # unsetopt correct
    unsetopt correctall

    zstyle ':completion:*' rehash true

    eval $(thefuck --alias)

    clear
    alias zshconfig="$EDITOR ~/.zshrc"
    printf "$fg[blue]ZSH Initialized $fg[reset]\n"
else
    printf "$fg[green]ZSH $fg[bold]RELOADED$fg[reset]\n"
fi

rm /tmp/.zshreload &> /dev/null
source /root/.zsh/alias.zsh
source /root/.zsh/functions.zsh
